about/urls.py
from django.urls import path

from about.views import AboutTemplateView
app_name = 'about'
urlpatterns = [
    path('', AboutTemplateView.as_view(), name='about')
]

blog/urls.py
from django.urls import path

from blog.views import Blogview, BlogDetailView, CommentCreateView


app_name='blog'
urlpatterns = [
    path('', Blogview.as_view(), name='view' ),
    path('detail/<int:pk>/', CommentCreateView.as_view(), name='comment' ),
    path('detail/<int:pk>comment/', BlogDetailView.as_view(), name='detail'),

]

contact/urls.py
from django.urls import path

from contact.views import  ContactCreateView

app_name='contact'
urlpatterns = [
    path('', ContactCreateView.as_view(), name='contact')
]

djangoContra/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('registration.backends.default.urls')),
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('about/', include('about.urls', namespace='about')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('project/', include('projects.urls', namespace='project')),
    path('shop/', include('shop1.urls', namespace='shop'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from home.views import HomeView, ServiceDetailView

app_name = 'home'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('detail/<int:pk>service/', ServiceDetailView.as_view(), name='service')
]

shop1/urls.py
from django.urls import path

from shop1.views import ProductListView, ProductDetailView

app_name = 'shop1'
urlpatterns  = [
    path('', ProductListView.as_view(), name='list'),
    path('<int:pk>/', ProductDetailView.as_view(), name='detail')
]

templates/layouts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<!-- contact27:42-->
<head>
<meta charset="utf-8">
<title>Contra - Interior Creator HTML Template | Contact</title>
<!-- Stylesheets -->
<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'css/style.css' %}" rel="stylesheet">
<link href="{% static 'css/responsive.css' %}" rel="stylesheet">
<!--Color Switcher Mockup-->
<link href="{% static 'css/color-switcher-design.css' %}" rel="stylesheet">
<!--Color Themes-->
<link id="theme-color-file" href="{% static 'css/color-themes/default-theme.css' %}" rel="stylesheet">

<link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type="image/x-icon">
<link rel="icon" href="{% static 'images/favicon.png' %}" type="image/x-icon">
<!-- Responsive -->
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
<!--[if lt IE 9]><script src="{% static 'https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js' %}"></script><![endif]-->
<!--[if lt IE 9]><script src="{% static 'js/respond.js' %}"></script><![endif]-->
</head>

<body>

<div class="page-wrapper">
    <!-- Preloader -->
    <div class="preloader"></div>

        <!-- Main Header-->
   {% include 'layouts/header.html' %}
    <!--End Main Header -->

    <!--Page Title-->
    <section class="page-title" style="background-image:url({% static 'images/background/10.jpg' %});">
        <div class="auto-container">
            <div class="inner-container clearfix">
                <div class="title-box">
                    <h1>Contact Us</h1>
                    <span class="title">The Interior speak for themselves</span>
                </div>
                <ul class="bread-crumb clearfix">
                    <li><a href="{% url 'home:home' %}">Home</a></li>
                    <li>Contact Us</li>
                </ul>
            </div>
        </div>
    </section>
    <!--End Page Title-->

    <!-- Contact Page Section -->
   {% block content %}{% endblock %}
    <!--End Contact Page Section -->

    <!--Clients Section-->
    <section class="clients-section style-two">
        <div class="auto-container">
            <div class="sponsors-outer">
                <!--Sponsors Carousel-->
                <ul class="sponsors-carousel owl-carousel owl-theme">
                    <li class="slide-item"><figure class="image-box"><a href="#"><img src="{% static 'images/clients/1.png' %}" alt=""></a></figure></li>
                    <li class="slide-item"><figure class="image-box"><a href="#"><img src="{% static 'images/clients/2.png' %}" alt=""></a></figure></li>
                    <li class="slide-item"><figure class="image-box"><a href="#"><img src="{% static 'images/clients/3.png' %}" alt=""></a></figure></li>
                    <li class="slide-item"><figure class="image-box"><a href="#"><img src="{% static 'images/clients/4.png' %}" alt=""></a></figure></li>
                    <li class="slide-item"><figure class="image-box"><a href="#"><img src="{% static 'images/clients/5.png' %}" alt=""></a></figure></li>
                    <li class="slide-item"><figure class="image-box"><a href="#"><img src="{% static 'images/clients/1.png' %}" alt=""></a></figure></li>
                    <li class="slide-item"><figure class="image-box"><a href="#"><img src="{% static 'images/clients/2.png' %}" alt=""></a></figure></li>
                    <li class="slide-item"><figure class="image-box"><a href="#"><img src="{% static 'images/clients/3.png' %}" alt=""></a></figure></li>
                    <li class="slide-item"><figure class="image-box"><a href="#"><img src="{% static 'images/clients/4.png' %}" alt=""></a></figure></li>
                    <li class="slide-item"><figure class="image-box"><a href="#"><img src="{% static 'images/clients/5.png' %}" alt=""></a></figure></li>
                </ul>
            </div>
        </div>
    </section>
    <!--End Clients Section-->

    <!-- Main Footer -->
    {% include 'layouts/footer.html' %}
    <!-- End Main Footer -->

</div>



<!--Scroll to top-->
<div class="scroll-to-top scroll-to-target" data-target="html"><span class="fa fa-arrow-circle-o-up"></span></div>
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.fancybox.js' %}"></script>
<script src="{% static 'js/owl.js' %}"></script>
<script src="{% static 'js/wow.js' %}"></script>
<script src="{% static 'js/appear.js' %}"></script>
<script src="{% static 'js/validate.js' %}"></script>
<script src="{% static 'js/mixitup.js' %}"></script>
<!--Google Map APi Key-->
<script src="http://maps.google.com/maps/api/js?key=AIzaSyBKS14AnP3HCIVlUpPKtGp7CbYuMtcXE2o"></script>
<script src="{% static 'js/map-script.js' %}"></script>
<!--End Google Map APi-->
<script src="{% static 'js/script.js' %}"></script>
<!-- Color Setting -->
<script src="{% static 'js/color-settings.js' %}"></script>
</body>

<!-- contact27:43-->
</html>

templates/layouts/footer.html
{% load static %}

<footer class="main-footer alternate" style="background-image: url({% static 'images/background/5.jpg' %});">
        <div class="auto-container">
            <!--Widgets Section-->
            <div class="widgets-section">
                <div class="row">
                    <!--Big Column-->
                    <div class="big-column col-xl-7 col-lg-12 col-md-12 col-sm-12">
                        <div class="row">
                            <!--Footer Column-->
                            <div class="footer-column col-xl-6 col-lg-6 col-md-6 col-sm-12">
                                <div class="footer-widget about-widget">
                                    <div class="footer-logo">
                                        <figure>
                                            <a href="/"><img src="{% static 'images/footer-logo.png' %}" alt=""></a>
                                        </figure>
                                    </div>
                                    <div class="widget-content">
                                        <div class="text">Contra and layouts, in content of dummy text is nonsensical.typefaces of dummy text is appearance of different general the content of dummy text is nonsensical. typefaces of dummy text is nonsensical.</div>
                                    </div>
                                </div>
                            </div>

                            <!--Footer Column-->
                            <div class="footer-column col-xl-6 col-lg-6 col-md-6 col-sm-12">
                                <div class="footer-widget recent-posts">
                                    <h2 class="widget-title">Recent Posts</h2>
                                     <!--Footer Column-->
                                    <div class="widget-content">
                                        <div class="post">
                                            <div class="thumb"><a href="blog-detail.html"><img src="{% static 'images/resource/post-thumb-1.jpg' %}" alt=""></a></div>
                                            <h4><a href="blog-detail.html">Triangle Concrete House on lake</a></h4>
                                            <ul class="info">
                                                <li>26 Aug</li>
                                                <li>3 Comments</li>
                                            </ul>
                                        </div>

                                        <div class="post">
                                            <div class="thumb"><a href="blog-detail.html"><img src="{% static 'images/resource/post-thumb-2.jpg' %}" alt=""></a></div>
                                            <h4><a href="blog-detail.html">The Amazing Interior for the Hotel art</a></h4>
                                            <ul class="info">
                                                <li>26 Aug</li>
                                                <li>3 Comments</li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!--Big Column-->
                    <div class="big-column col-xl-5 col-lg-12 col-md-12 col-sm-12">
                        <div class="row clearfix">
                            <div class="footer-column col-xl-5 col-lg-6 col-md-6 col-sm-12">
                                 <div class="footer-widget links-widget">
                                    <h2 class="widget-title">Useful links</h2>
                                    <div class="widget-content">
                                        <ul class="list">
                                            <li><a href="about.html">About</a></li>
                                            <li><a href="services.html">Services</a></li>
                                            <li><a href="projects.html">Project</a></li>
                                            <li><a href="blog-classic.html">News</a></li>
                                            <li><a href="contact.html">Contact Us</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>

                            <!--Footer Column-->
                            <div class="footer-column col-xl-7 col-lg-6 col-md-6 col-sm-12">
                                <div class="footer-widget gallery-widget">
                                    <h2 class="widget-title">Recent Works</h2>
                                    <div class="widget-content">

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!--Footer Bottom-->
        <div class="footer-bottom">
            <div class="auto-container">
                <div class="inner-container clearfix">
                    <div class="social-links">
                        <ul class="social-icon-two">
                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                            <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                            <li><a href="#"><i class="fa fa-whatsapp"></i></a></li>
                        </ul>
                    </div>

                    <div class="copyright-text">
                       <a href="https://www.templateshub.net" target="_blank">Templates Hub</a>
                    </div>
                </div>
            </div>
        </div>
    </footer>

templates/layouts/header.html
{% load static %}
<header class="main-header header-style-four">

    <div class="header-lower">
        <div class="auto-container">
            <div class="main-box clearfix">
                <div class="logo-box">
                    <div class="logo"><a href="{% url 'home:home' %}"><img src="{% static 'images/logo-2.png' %}" alt=""
                                                                           title=""></a></div>
                </div>

                <div class="nav-outer">
                    <!-- Main Menu -->
                    <nav class="main-menu navbar-expand-md ">
                        <div class="navbar-header">
                            <!-- Toggle Button -->
                            <button class="navbar-toggler" type="button" data-toggle="collapse"
                                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                                    aria-expanded="false" aria-label="Toggle navigation">
                                <span class="icon flaticon-menu-button"></span>
                            </button>
                        </div>

                        <div class="collapse navbar-collapse clearfix" id="navbarSupportedContent">
                            <ul class="navigation clearfix">
                                {% url 'home:home' as home %}
                                <li class="{% if request.path == home %}active{% endif %}">
                                    <a href="{{ home }}">Home</a>
                                    <ul>

                                    </ul>
                                </li>
                                <li class=""><a href="{% url 'about:about' %}">About</a>



                                </li>
                                <li class="dropdown"><a href="{% url 'project:project' %}">Projects</a>

                                </li>
                                <li {% if request.path == '/Blog/' %}class="active"{% endif %}><a
                                        href="{% url 'blog:view' %}">Blog</a>

                                </li>
                                <li class="dropdown"><a href="{% url 'shop:list' %}">Shop</a>

                                </li>
                                <li class="active"><a href="{% url 'contact:contact' %}">Contact</a></li>
                                <li class="dropdown">
                                    <a href=""> <svg xmlns="http://www.w3.org/2000/svg" width="16" height="29" fill="currentColor"
                                         class="bi bi-cart" viewBox="0 0 16 16">
                                        <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                                </svg></a>
                                </li>


                            </ul>
                        </div>
                    </nav><!-- Main Menu End-->

                    <!-- Outer Box-->
                    <div class="outer-box">
                        <!--Search Box-->
                        <div class="search-box-outer">
                            <div class="dropdown">
                                <button class="search-box-btn dropdown-toggle" type="button" id="dropdownMenu3"
                                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span
                                        class="fa fa-search"></span></button>
                                <ul class="dropdown-menu pull-right search-panel" aria-labelledby="dropdownMenu3">
                                    <li class="panel-outer">
                                        <div class="form-container">
                                            <form  action="{% url 'shop:list' %}">
                                                <div class="form-group">
                                                    <input type="text" name="q" value=""
                                                           placeholder="Search Here">
                                                    <button type="submit" class="search-btn"><span
                                                            class="fa fa-search"></span></button>
                                                </div>
                                            </form>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>