about/urls.py
from django.urls import path

from about.views import AboutTemplateView
app_name = 'about'
urlpatterns = [
    path('', AboutTemplateView.as_view(), name='about')
]

blog/urls.py
from django.urls import path

from blog.views import Blogview, BlogDetailView, CommentCreateView


app_name='blog'
urlpatterns = [
    path('', Blogview.as_view(), name='view' ),
    path('detail/<int:pk>/', CommentCreateView.as_view(), name='comment' ),
    path('detail/<int:pk>comment/', BlogDetailView.as_view(), name='detail'),

]

contact/urls.py
from django.urls import path

from contact.views import  ContactCreateView

app_name='contact'
urlpatterns = [
    path('', ContactCreateView.as_view(), name='contact')
]

home/urls.py
from django.urls import path

from home.views import HomeView, ServiceDetailView

app_name = 'home'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('detail/<int:pk>service/', ServiceDetailView.as_view(), name='service')
]

projects/urls.py
from django.urls import path

from projects.views import ProjectView, ProjectDetailView

app_name = 'projects'
urlpatterns = [
    path('', ProjectView.as_view(), name='project'),
    path('<int:pk>/', ProjectDetailView.as_view(), name='detail')
]

about/models.py
from django.db import models

class AboutModel(models.Model):
    title = models.CharField(max_length=100)
    content = models.CharField(max_length=255)
    image = models.ImageField()
    created_at = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'about'
        verbose_name_plural = 'about'


class FeaturesModel(models.Model):
    title = models.CharField(max_length=255)
    icon = models.ImageField()
    long_text = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'feature'
        verbose_name_plural = 'features'


class ClientModel(models.Model):
    name = models.CharField(max_length=15)
    image = models.ImageField()
    content = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)



    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'client'
        verbose_name_plural = 'clients'


class ProcessModel(models.Model):
    number = models.IntegerField()
    title = models.CharField(max_length=255)
    long_desc = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.title

    class Meta:
         verbose_name = 'process'
         verbose_name_plural = 'processes'

class VideoModel(models.Model):
    title = models.CharField(max_length=255)
    suggestion = models.CharField(max_length=100)
    about_video = models.CharField(max_length=200)
    video = models.FileField()
    created_at = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'video'
        verbose_name_plural = 'videos'

blog/models.py
from django.db import models
#
# class CategoryModel(models.Model):
#     title = models.CharField(max_length=100,default=None )
#     created_at = models.DateTimeField(auto_now_add=True)
#
#
#     def __str__(self):
#         return self.title
#
#     class Meta:
#         verbose_name = 'category'
#         verbose_name_plural = 'categories'


class AuthorModel(models.Model):
    title = models.CharField(max_length=200, default=True)
    name = models.CharField(max_length=50)
    image = models.ImageField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'author'
        verbose_name_plural = 'authors'


class PostTagModel(models.Model):
    title = models.CharField(max_length=75)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'tag'
        verbose_name_plural = 'tags'


class PostModel(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField()
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(AuthorModel, on_delete=models.PROTECT, related_name='posts')
    tags = models.ManyToManyField(PostTagModel, related_name='posts')
    # category = models.ForeignKey(CategoryModel, default=None, on_delete=models.CASCADE, related_name='posts')

    def get_comments(self):
        return self.comments.order_by('-created_at')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'

class CommentModel(models.Model):
    post = models.ForeignKey(PostModel, related_name='comments', on_delete=models.CASCADE)
    name = models.CharField(max_length=30)
    email = models.EmailField()
    phone = models.IntegerField( blank=True, null=True)
    comment = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'comment'
        verbose_name_plural = 'comments'

contact/models.py
from django.db import models

class ContactModel(models.Model):
    name = models.CharField(max_length=255)
    company = models.CharField(max_length=255)
    message = models.TextField()
    phone = models.IntegerField()
    email = models.EmailField()
    created_at = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'contact'
        verbose_name_plural = 'contacts'

projects/models.py
from django.db import models

class CategoryModel(models.Model):
    title = models.CharField(max_length=255)


    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'


class projectModel(models.Model):
    name = models.CharField(max_length=100)
    title = models.CharField(max_length=255)
    image = models.ImageField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title



    class Meta:
        verbose_name = 'project'
        verbose_name_plural = 'projects'

services/models.py
from django.db import models

# Create your models here.

blog/forms.py
from django import forms

from blog.models import CommentModel


class CommentModelForm(forms.ModelForm):
    class Meta:
        model = CommentModel
        exclude = ['created_at', 'post']

contact/forms.py
from django import forms

from contact.models import ContactModel


class ContactModelForm(forms.ModelForm):
    class Meta:
        model = ContactModel
        exclude = ['created_at']

about/views.py
from django.shortcuts import render
from django.views.generic import ListView

from about.models import AboutModel, FeaturesModel, ClientModel, ProcessModel, VideoModel


class AboutTemplateView(ListView):
    template_name = 'about.html'
    model = AboutModel

    def get_context_data(self, **kwargs):
        context = super(AboutTemplateView, self).get_context_data(**kwargs)
        context['info'] = AboutModel.objects.all()
        context['features'] = FeaturesModel.objects.all()[:3]
        context['clients'] = ClientModel.objects.all()
        context['processes'] = ProcessModel.objects.all()
        context['videos'] = VideoModel.objects.all()

        return context

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views.generic import ListView, DetailView, CreateView

from blog.forms import CommentModelForm
from blog.models import AuthorModel, PostModel


class Blogview(ListView):
    template_name = 'blog.html'


    def get_queryset(self):
        qs = PostModel.objects.all
        # q = self.request.GET.get('q')
        # cat = self.request.GET.get('cat')
        #
        # if q:
        #     qs.filter(title__icontains=q)
        #
        # if cat:
        #     qs = qs.filter(category_id=cat)

        return qs

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data()
    #     context['categories'] = CategoryModel.objects.order_by('-pk')
    #     return context


class BlogDetailView(DetailView):
    template_name = 'blog-detail.html'
    model = PostModel

class CommentCreateView(CreateView):
    form_class = CommentModelForm

    def form_valid(self, form):
        form.instance.post = get_object_or_404(PostModel, pk=self.kwargs.get('pk'))
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:detail', kwargs={'pk':self.kwargs.get('pk')})

contact/views.py
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import  CreateView

from contact.forms import ContactModelForm



class ContactCreateView(CreateView):
    template_name = 'contact.html'
    form_class = ContactModelForm

    def get_success_url(self):
        return reverse('contact:contact')

projects/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from projects.models import projectModel, CategoryModel


class ProjectView(ListView):
    template_name = 'projects.html'
    queryset = projectModel

    def get_context_data(self, **kwargs):
        context = super(ProjectView, self).get_context_data(**kwargs)
        context['categories'] = CategoryModel.objects.all()
        context['projects'] = projectModel.objects.all()

        return context

class ProjectDetailView(DetailView):
    template_name = 'project-detail.html'
    model = projectModel

services/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}{% endblock %}
</body>
</html>

templates/coming-soon.html
<!DOCTYPE html>
<html lang="en">

<!-- coming-soon27:08-->
<head>
<meta charset="utf-8">
<title>Contra - Interior Creator HTML Template | Coming Soon</title>
<!-- Stylesheets -->
<link href="css/bootstrap.css" rel="stylesheet">
<link href="css/style.css" rel="stylesheet">
<link href="css/responsive.css" rel="stylesheet">   
<!--Color Switcher Mockup-->
<link href="css/color-switcher-design.css" rel="stylesheet">
<!--Color Themes-->
<link id="theme-color-file" href="css/color-themes/default-theme.css" rel="stylesheet">

<link rel="shortcut icon" href="images/favicon.png" type="image/x-icon">
<link rel="icon" href="images/favicon.png" type="image/x-icon">
<!-- Responsive -->
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
<!--[if lt IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js"></script><![endif]-->
<!--[if lt IE 9]><script src="js/respond.js"></script><![endif]-->
</head>

<body>

<div class="page-wrapper">
    <!-- Preloader -->
    <div class="preloader"></div>

    <!-- Coming Soon -->
    <section class="coming-soon" style="background-image:url(images/background/3.jpg)">
        <div class="auto-container">
            <div class="content">
                <div class="content-inner">
                    <div class="logo"><a href="index-2.html"><img src="images/logo-2.png" alt="" /></a></div>
                    <h2>Comming Soon</h2>
                    <div class="time-counter"><div class="time-countdown clearfix" data-countdown="2019/9/19"></div></div>
                    <div class="text">Our Website is under construction. stay tuned for something amazing!. <br> Subscribe to be notified,</div>
                    <!--Emailed Form-->
                    <div class="emailed-form">
                        <form method="post" action="#">
                            <div class="form-group">
                                <input type="email" name="email" value="" placeholder="Enter Your Email" required>
                                <button type="submit" class="theme-btn btn-style-one">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- End Coming Soon -->
</div>



<!--Scroll to top-->
<div class="scroll-to-top scroll-to-target" data-target="html"><span class="fa fa-arrow-circle-o-up"></span></div>
<script src="js/jquery.js"></script> 
<script src="js/popper.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/jquery.fancybox.js"></script>
<script src="js/owl.js"></script>
<script src="js/wow.js"></script>
<script src="js/jquery.countdown.js"></script>
<script src="js/appear.js"></script>
<script src="js/script.js"></script>
<!-- Color Setting -->
<script src="js/color-settings.js"></script>
</body>

<!-- coming-soon27:08-->
</html>

templates/index.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block content %}
     <section class="banner-section">
        <div class="banner-carousel owl-carousel owl-theme">
            <div class="slide-item" style="background-image: url({% static 'images/main-slider/image-1.jpg' %});">
                <div class="auto-container">
                    <div class="content-box">
                        <h2>Architecture is a <br> Visual Art.</h2>
                        <div class="text">The buildings speak for themselves</div>
                        <div class="link-box">
                            <a href="{% url 'about:about' %}" class="theme-btn btn-style-one">Check Art</a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="slide-item" style="background-image: url({% static 'images/main-slider/image-2.jpg' %});">
                <div class="auto-container">
                    <div class="content-box">
                        <h2>Architecture is a <br> Visual Art.</h2>
                        <div class="text">The buildings speak for themselves</div>
                        <div class="link-box">
                            <a href="about.html" class="theme-btn btn-style-one">Check Art</a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="slide-item" style="background-image: url({% static 'images/main-slider/image-3.jpg' %});">
                <div class="auto-container">
                    <div class="content-box">
                        <h2>Architecture is a <br> Visual Art.</h2>
                        <div class="text">The buildings speak for themselves</div>
                        <div class="link-box">
                            <a href="about.html" class="theme-btn btn-style-one">Check Art</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="bottom-box">
            <div class="auto-container clearfix">
                <ul class="contact-info">
                    <li><span>Phone :</span> (+84) 867-557-243</li>
                    <li><span>EMAIL :</span> <a href="#">Support@yourdomain.com</a></li>
                </ul>
            </div>
        </div>
    </section>
    <!-- End Bnner Section -->

    <!-- About Section -->

    <!--End About Section -->

    <!-- Services Section -->
    <section class="services-section">
        <div class="upper-box" style="background-image: url({% static 'images/background/2.jpg' %});">
            <div class="auto-container">
                <div class="sec-title text-center light">
                    <span class="float-text">Specialization</span>
                    <h2>Our Specialization</h2>
                </div>
            </div>
        </div>

        <div class="services-box">
            <div class="auto-container">
                <div class="services-carousel owl-carousel owl-theme">
                    {% for post in special %}
                    <div class="service-block">
                        <div class="inner-box">
                            <div class="image-box">
                                <figure class="image"><a href="service-detail.html"><img src="{{ post.image.url }}" alt=""></a></figure>
                            </div>
                            <div class="lower-content">
                                <h3><a href="service-detail.html">{{ post.title }}</a></h3>
                                <div class="text">{{ post.description }}.</div>
                                <div class="link-box">
                                    <a href="{% url 'home:service' pk=post.pk%}">Learn More <i class="fa fa-long-arrow-right"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}

                    <!-- Service Block -->

                </div>
            </div>
        </div>
    </section>
    <!--End Services Section -->

    <!-- Fun Fact Section -->
    <section class="fun-fact-section">
        <div class="outer-box" style="background-image: url({% static 'images/background/3.jpg' %});">
            <div class="auto-container">
                <div class="fact-counter">
                    <div class="row">
                        <!--Column-->
                        <div class="counter-column col-lg-3 col-md-6 col-sm-12 wow fadeInUp">
                            <div class="count-box">
                                <div class="count"><span class="count-text" data-speed="5000" data-stop="14">0</span></div>
                                <h4 class="counter-title">Years of <br>Experience</h4>
                            </div>
                        </div>

                        <!--Column-->
                        <div class="counter-column col-lg-3 col-md-6 col-sm-12 wow fadeInUp" data-wow-delay="400ms">
                            <div class="count-box">
                                <div class="count"><span class="count-text" data-speed="5000" data-stop="237">0</span></div>
                                <h4 class="counter-title">Project <br>Taken</h4>
                            </div>
                        </div>

                        <!--Column-->
                        <div class="counter-column col-lg-3 col-md-6 col-sm-12 wow fadeInUp" data-wow-delay="800ms">
                            <div class="count-box">
                                <div class="count"><span class="count-text" data-speed="5000" data-stop="11">0</span>K</div>
                                <h4 class="counter-title">Twitter <br> Follower</h4>
                            </div>
                        </div>

                        <!--Column-->
                        <div class="counter-column col-lg-3 col-md-6 col-sm-12 wow fadeInUp" data-wow-delay="1200ms">
                            <div class="count-box">
                                <div class="count"><span class="count-text" data-speed="5000" data-stop="12">0</span></div>
                                <h4 class="counter-title">Awards<br>won</h4>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--End Fun Fact Section -->

    <!-- Project Section -->
    <section class="projects-section">
        <div class="auto-container">
            <div class="sec-title text-right">
                <span class="float-text">Project</span>
                <h2>Our Project</h2>
            </div>
        </div>

        <div class="inner-container">
            <div class="projects-carousel owl-carousel owl-theme">
                {% for project in projects %}
                <div class="project-block">
                    <div class="image-box">
                        <figure class="image"><img src="{{ project.image.url }}" alt=""></figure>
                        <div class="overlay-box">
                            <h4><a href="project-detail.html">{{ project.title }}</a></h4>
                            <div class="btn-box">
                                <a href="{% static 'images/clients/5.png' %}" class="lightbox-image" data-fancybox="gallery"><i class="fa fa-search"></i></a>
                                <a href="project-detail.html"><i class="fa fa-external-link"></i></a>
                            </div>
                            <span class="tag">{{ project.type }}</span>
                        </div>
                    </div>
                </div>
                {% endfor %}

                <!-- Project Block -->

            </div>
        </div>
    </section>
    <!--End Project Section -->

    <!-- Team Section -->
    <section class="team-section">
        <div class="auto-container">
            <div class="sec-title text-center">
                <span class="title">Our Team</span>
                <h2>Profect Expert</h2>
            </div>

            <div class="row clearfix">
               {% for team in staff %}
                <div class="team-block col-lg-4 col-md-6 col-sm-12">
                    <div class="inner-box">
                        <div class="image-box">
                            <div class="image"><a href="team.html"><img width="auto" src="{{ team.photo.url }}" alt=""></a></div>
                            <ul class="social-links">
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                                <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                                <li><a href="#"><i class="fa fa-whatsapp"></i></a></li>
                            </ul>
                            <h3 class="name"><a href="team.html">{{ team.name }}</a></h3>
                        </div>
                        <span class="designation">{{ team.job }}</span>
                    </div>
                </div>
                {% endfor %}



            </div>
        </div>
    </section>
    <!--End Team Section -->

    <!-- Testimonial Section -->
    <section class="testimonial-section">
        <div class="outer-container clearfix">
            <!-- Title Column -->
            <div class="title-column clearfix">
                <div class="inner-column">
                    <div class="sec-title">
                        <span class="float-text">testimonial</span>
                        <h2>What Client Says</h2>
                    </div>
                    <div class="text">Looking at its layout. The point of using very profectly is that it has a more-or-less normal distribution of letters, as opposed</div>
                </div>
            </div>

            <!-- Testimonial Column -->
            <div class="testimonial-column clearfix" style="background-image: url({% static 'images/background/4.jpg' %});">
                <div class="inner-column">
                    <div class="testimonial-carousel owl-carousel owl-theme">
                        {% for client in clients %}
                        <div class="testimonial-block">
                            <div class="inner-box">
                                <div class="image-box"><img src="{{ client.picture.url }}" alt=""></div>
                                <div class="text">A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot.</div>
                                <div class="info-box">
                                    <h4 class="name">{{ client.name }}</h4>
                                    <span class="designation">{{ client.job }}</span>
                                </div>
                            </div>
                        </div>

                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--End Testimonial Section -->

    <!-- News Section -->
    <section class="news-section">
        <div class="auto-container">
            <div class="sec-title">
                <span class="float-text">Blogs</span>
                <h2>News & Articals</h2>
            </div>
            <div class="row">
                {% for info in news %}
                <div class="news-block col-lg-4 col-md-6 col-sm-12">
                    <div class="inner-box">
                        <div class="image-box">
                            <figure class="image"><img src="{{ info.image.url }}" alt=""></figure>
                            <div class="overlay-box"><a href="blog-detail.html"><i class="fa fa-link"></i></a></div>
                        </div>
                        <div class="caption-box">
                            <h3><a href="{% url 'blog:detail' pk=info.pk %}">{{ info.title }}</a></h3>
                            <ul class="info">
                                <li>{{ info.created_at }}</li>
                                <li>{{ info.post_by }}</li>
                            </ul>
                        </div>
                    </div>
                </div>
                {% endfor %}


            </div>
        </div>
    </section>
    <!--End News Section -->

    <!--Clients Section-->
    <section class="clients-section">
        <div class="inner-container">
            <div class="sponsors-outer">
                <!--Sponsors Carousel-->
                <ul class="sponsors-carousel owl-carousel owl-theme">
                    {% for partner in partners %}
                    <li class="slide-item"><figure class="image-box"><a href="#"><img src="{{ partner.logo.url }}" alt=""></a></figure></li>
                    {% endfor %}

                </ul>
            </div>
        </div>
    </section>
    <!--End Clients Section-->

{% endblock %}

templates/projects.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block content %}
     <section class="projects-section alternate">
        <div class="auto-container">
             <!--MixitUp Galery-->
            <div class="mixitup-gallery">
                <!--Filter-->
                <div class="filters text-center clearfix">
                    <ul class="filter-tabs filter-btns clearfix">
                        {% for category in categories %}
                        <li class="active filter" data-role="button" data-filter="all">{{ category.title }}</li>
                        {% endfor %}

                    </ul>
                </div>

                <div class="filter-list row">
                    {% for post in projects %}
                    <div class="project-block all mix interior architecture landescape col-lg-4 col-md-6 col-sm-12">
                        <div class="image-box">
                            <figure class="image"><img src="{% static 'images/gallery/2-1.jpg' %}" alt=""></figure>
                            <div class="overlay-box">
                                <h4><a href="{% url 'project:detail' pk=post.pk %}">{{ post.name }}</a></h4>
                                <div class="btn-box">
                                    <a href="{{ post.image.url }}" class="lightbox-image" data-fancybox="gallery"><i class="fa fa-search"></i></a>
                                    <a href="{% url 'project:detail' pk=post.pk %}"><i class="fa fa-external-link"></i></a>
                                </div>
                                <span class="tag">{{ post.title }}</span>
                            </div>
                        </div>
                    </div>
                    {% endfor %}




                </div>
            </div>

            <!--Post Share Options-->
            <div class="styled-pagination">
                <ul class="clearfix">
                    <li class="prev-post"><a href="#"><span class="fa fa-long-arrow-left"></span> Prev</a></li>
                    <li><a href="#">1</a></li>
                    <li class="active"><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li class="next-post"><a href="#"> Next <span class="fa fa-long-arrow-right"></span> </a></li>
                </ul>
            </div>
        </div>
    </section>
{% endblock %}